# Generated by Django 5.1.3 on 2024-12-17 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('karatestyles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='movimentos/')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='style', to='karatestyles.karatestyle')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
