# Generated by Django 5.1.3 on 2025-09-17 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dojos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_students', models.IntegerField(default=0)),
                ('last_exam_date', models.DateField(blank=True, null=True)),
                ('last_exam_participants', models.IntegerField(default=0)),
                ('last_exam_approved', models.IntegerField(default=0)),
                ('last_exam_students', models.JSONField(blank=True, default=list)),
                ('next_exam_date', models.DateField(blank=True, null=True)),
                ('next_exam_registered', models.IntegerField(default=0)),
                ('next_exam_students', models.JSONField(blank=True, default=list)),
                ('next_exam_name', models.CharField(blank=True, max_length=255)),
                ('upcoming_events', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='dojos.dojo')),
            ],
        ),
    ]
