# Generated by Django 5.1.3 on 2025-09-16 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('graduations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('EXAME', 'Exame de Faixa'), ('TREINO', 'Treinamento Especial'), ('CAMPEONATO', 'Campeonato'), ('SEMINARIO', 'Seminário'), ('OUTRO', 'Outro')], max_length=20)),
                ('level', models.CharField(choices=[('INTERNO', 'Interno (Clube/Dojô)'), ('MUNICIPAL', 'Municipal'), ('REGIONAL', 'Regional'), ('ESTADUAL', 'Estadual'), ('NACIONAL', 'Nacional'), ('INTERNACIONAL', 'Internacional'), ('FESTIVO', 'Festivo/Exibição')], max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('local', models.CharField(max_length=300)),
                ('adress', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('INFANTIL', 'Infantil'), ('JUVENIL', 'Juvenil'), ('ADULTO', 'Adulto'), ('MASTER', 'Master')], max_length=30)),
                ('modalitiy', models.CharField(choices=[('KATA', 'Kata'), ('KUMITE', 'Kumite'), ('KATATEAM', 'Kata Equipe'), ('KUMITETEAM', 'Kumite Equipe')], max_length=30)),
                ('registration_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('limite_date', models.DateField(blank=True, null=True)),
                ('organizer', models.CharField(blank=True, max_length=150, null=True)),
                ('event_organizer', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('AUSENTE', 'Ausente')], max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hability_graduation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='event_graduation', to='graduations.graduation')),
            ],
        ),
    ]
