# Generated by Django 5.1.3 on 2025-11-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='kind',
            field=models.CharField(choices=[('TREINO', 'Treinamento Especial'), ('CAMPEONATO', 'Campeonato'), ('SEMINARIO', 'Seminário'), ('OUTRO', 'Outro')], max_length=20),
        ),
    ]
