# Generated by Django 5.1.3 on 2025-11-05 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_kind'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='modalitiy',
            new_name='modality',
        ),
    ]
