# Generated by Django 5.1.3 on 2025-11-05 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rename_modalitiy_event_modality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='adress',
            new_name='address',
        ),
    ]
