# Generated by Django 5.1.3 on 2025-11-06 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_rename_adress_event_address'),
        ('graduations', '0001_initial'),
        ('karatecas', '0006_remove_karateca_monthlypay_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_organizer',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='event',
            name='hability_graduation',
        ),
        migrations.AlterField(
            model_name='event',
            name='kind',
            field=models.CharField(choices=[('Curso', 'Curso'), ('Treino Especial', 'Treino Especial'), ('Campeonato', 'Campeonato'), ('Outros', 'Outros')], max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='level',
            field=models.CharField(choices=[('Regional', 'Regional'), ('Estadual', 'Estadual'), ('Nacional', 'Nacional'), ('Internacional', 'Internacional')], max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='limite_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='local',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='event',
            name='modality',
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('Encerrado', 'Encerrado'), ('Cancelado', 'Cancelado')], default='Aberto', max_length=20),
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('karateca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karatecas.karateca')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='events_participated', through='events.CourseEnrollment', to='karatecas.karateca'),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='events_categories', to='events.category'),
        ),
        migrations.AddField(
            model_name='event',
            name='hability_graduation',
            field=models.ManyToManyField(blank=True, related_name='events_graduations', to='graduations.graduation'),
        ),
        migrations.AddField(
            model_name='event',
            name='modality',
            field=models.ManyToManyField(blank=True, related_name='events_modalities', to='events.modality'),
        ),
    ]
