# Generated by Django 5.1.3 on 2025-11-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_category_modality_remove_event_created_at_and_more'),
        ('graduations', '0001_initial'),
        ('karatecas', '0006_remove_karateca_monthlypay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ManyToManyField(blank=True, to='events.category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='hability_graduation',
            field=models.ManyToManyField(blank=True, to='graduations.graduation'),
        ),
        migrations.AlterField(
            model_name='event',
            name='modality',
            field=models.ManyToManyField(blank=True, to='events.modality'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='event_participations', through='events.CourseEnrollment', to='karatecas.karateca'),
        ),
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together={('event', 'karateca')},
        ),
    ]
