# Generated by Django 5.1.3 on 2025-10-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_type', models.CharField(choices=[('MONTHLY', 'Mensalidade'), ('COURSE', 'Curso'), ('EVENT', 'Evento')], max_length=20)),
                ('due_date', models.DateField()),
            ],
        ),
    ]
