# Generated by Django 5.1.3 on 2025-10-14 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('graduations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_categorie', models.CharField(max_length=150)),
                ('description', models.CharField(help_text='Descrição curta (ex: Branca para Amarela)', max_length=100)),
                ('current_graduation', models.ForeignKey(help_text='Graduação atual do karateca (ex: Branca)', on_delete=django.db.models.deletion.CASCADE, related_name='from_categories', to='graduations.graduation')),
                ('next_graduation', models.ForeignKey(help_text='Próxima graduação pretendida (ex: Amarela)', on_delete=django.db.models.deletion.CASCADE, related_name='to_categories', to='graduations.graduation')),
            ],
        ),
    ]
