# Generated by Django 5.1.3 on 2025-10-14 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examcategories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examcategory',
            name='current_graduation',
        ),
        migrations.RemoveField(
            model_name='examcategory',
            name='next_graduation',
        ),
    ]
