# Generated by Django 5.1.3 on 2025-10-14 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examcategories', '0002_remove_examcategory_current_graduation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examcategory',
            old_name='name_categorie',
            new_name='name_category',
        ),
    ]
