# Generated by Django 5.1.3 on 2026-03-30 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examcategories', '0003_rename_name_categorie_examcategory_name_category'),
        ('graduations', '0003_alter_graduation_min_months_alter_graduation_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcategory',
            name='to_graduation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam_target_categories', to='graduations.graduation'),
        ),
    ]
