# Generated by Django 5.1.3 on 2024-12-17 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('senseis', '0001_initial'),
        ('weekdays', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aulas', to='weekdays.weekday')),
                ('sensei', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='senseis', to='senseis.sensei')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
