# Generated by Django 5.1.3 on 2025-10-27 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billingCycle', '0001_initial'),
        ('karatecas', '0006_remove_karateca_monthlypay_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billing_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billingCycle.billingcycle')),
                ('karateca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karatecas.karateca')),
            ],
            options={
                'unique_together': {('karateca', 'billing_cycle')},
            },
        ),
    ]
