# Generated by Django 5.1.3 on 2025-10-24 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_alter_event_status'),
        ('karatecas', '0006_remove_karateca_monthlypay_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('billed', models.BooleanField(default=False)),
                ('event', models.ForeignKey(help_text='Curso ou Evento', on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('karateca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karatecas.karateca')),
            ],
        ),
    ]
