# Generated by Django 5.1.3 on 2024-12-17 16:38

import django.db.models.deletion
import expenses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('duedate', models.CharField(help_text='Insira dia e mês DD-MM', max_length=5, validators=[expenses.models.validate_day_month])),
                ('paid', models.BooleanField(default=True)),
                ('expenses', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
