# Generated by Django 5.1.3 on 2024-12-17 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dojos', '0001_initial'),
        ('genres', '0001_initial'),
        ('graduations', '0001_initial'),
        ('revenues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karateca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cpf', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('celphone', models.CharField(blank=True, max_length=60, null=True)),
                ('total_karatecas', models.IntegerField(blank=True, null=True)),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dojo', to='dojos.dojo')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genres', to='genres.genre')),
                ('graduation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='graduation', to='graduations.graduation')),
                ('monthlypay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensalidade', to='revenues.revenue')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
