# Generated by Django 5.1.3 on 2025-09-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karatecas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='karateca',
            name='active',
            field=models.CharField(blank=True, choices=[('ATIVO', 'Ativo'), ('AFASTADO', 'Afastado'), ('LICENCIADO', 'Licenciado'), ('CANCELADO', 'Desmatriculado')], max_length=60, null=True),
        ),
    ]
