# Generated by Django 5.1.3 on 2025-10-22 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0001_initial'),
        ('genres', '0001_initial'),
        ('graduations', '0001_initial'),
        ('karatecas', '0002_karateca_active'),
        ('revenues', '0003_alter_revenue_duedate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='karateca',
            options={'ordering': ['name'], 'verbose_name': 'Karateca', 'verbose_name_plural': 'Karatecas'},
        ),
        migrations.AddField(
            model_name='karateca',
            name='dan',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='karateca',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='karateka', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='karateca',
            name='active',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('AFASTADO', 'Afastado'), ('LICENCIADO', 'Licenciado'), ('CANCELADO', 'Desmatriculado')], default='ATIVO', max_length=60),
        ),
        migrations.AlterField(
            model_name='karateca',
            name='dojo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='karatekas', to='dojos.dojo'),
        ),
        migrations.AlterField(
            model_name='karateca',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='karatekas', to='genres.genre'),
        ),
        migrations.AlterField(
            model_name='karateca',
            name='graduation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='karatekas', to='graduations.graduation'),
        ),
        migrations.AlterField(
            model_name='karateca',
            name='monthlypay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='karatekas_mensalidade', to='revenues.revenue'),
        ),
    ]
