# Generated by Django 5.1.3 on 2025-10-22 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karatecas', '0003_alter_karateca_options_karateca_dan_karateca_user_and_more'),
        ('kindrevenues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karateca',
            name='monthlypay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensalidade', to='kindrevenues.kindrevenue'),
        ),
    ]
