# Generated by Django 5.1.3 on 2025-10-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karatecas', '0004_alter_karateca_monthlypay'),
    ]

    operations = [
        migrations.AddField(
            model_name='karateca',
            name='due_day',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='karateca',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
