# Generated by Django 5.1.3 on 2025-10-24 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karatecas', '0005_karateca_due_day_karateca_monthly_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karateca',
            name='monthlypay',
        ),
        migrations.RemoveField(
            model_name='karateca',
            name='total_karatecas',
        ),
    ]
