# Generated by Django 5.1.3 on 2026-02-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karatecas', '0006_remove_karateca_monthlypay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='karateca',
            name='graduation_date',
            field=models.DateField(blank=True, help_text='Data em que a graduação atual foi obtida', null=True),
        ),
    ]
