# Generated by Django 5.1.3 on 2026-05-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karatecas', '0007_karateca_graduation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='karateca',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
