# Generated by Django 5.1.3 on 2025-09-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examrequirement',
            name='max_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
