# Generated by Django 5.1.3 on 2025-09-18 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0001_initial'),
        ('exams', '0002_examrequirement_max_score'),
        ('karatecas', '0002_karateca_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='participants',
            field=models.ManyToManyField(related_name='exams', through='exams.ExamEnrollment', to='karatecas.karateca'),
        ),
        migrations.AddField(
            model_name='examenrollment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='dojo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='dojos.dojo'),
        ),
        migrations.AlterField(
            model_name='examenrollment',
            name='karateca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_enrollments', to='karatecas.karateca'),
        ),
    ]
