# Generated by Django 5.1.3 on 2025-09-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exam_participants_examenrollment_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenrollment',
            name='approved',
            field=models.BooleanField(default=False, help_text='Marca se o aluno foi aprovado no exame'),
        ),
    ]
