# Generated by Django 5.1.3 on 2025-09-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_examenrollment_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='comments',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
