# Generated by Django 5.1.3 on 2025-09-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_examresult_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.CharField(blank=True, choices=[('AGENDADO', 'Agendado'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado'), ('FINALIZADO', 'Finalizado')], max_length=60, null=True),
        ),
    ]
