# Generated by Django 5.1.3 on 2025-10-10 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_exam_status'),
        ('senseis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='sensei_examiner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='examiner', to='senseis.sensei'),
        ),
    ]
