# Generated by Django 5.1.3 on 2025-10-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_examresult_sensei_examiner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='sensei_examiner',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
