# Generated by Django 5.1.3 on 2025-10-14 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examcategories', '0003_rename_name_categorie_examcategory_name_category'),
        ('exams', '0008_alter_examresult_sensei_examiner'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Categorias de graduação que fazem parte do exame (ex: Branca -> Azul)', related_name='exams', to='examcategories.examcategory'),
        ),
        migrations.AddField(
            model_name='examenrollment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='examcategories.examcategory'),
        ),
        migrations.AlterField(
            model_name='examenrollment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
