# Generated by Django 5.1.3 on 2025-11-04 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examcategories', '0003_rename_name_categorie_examcategory_name_category'),
        ('exams', '0009_exam_categories_examenrollment_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examrequirement',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='examcategories.examcategory'),
        ),
    ]
