# Generated by Django 5.1.3 on 2026-04-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_examrequirement_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examrequirement',
            name='max_score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='examrequirement',
            name='min_score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
