# Generated by Django 5.1.3 on 2026-04-09 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examcategories', '0004_examcategory_to_graduation'),
        ('exams', '0011_alter_examrequirement_max_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examrequirement',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='examcategories.examcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='examrequirement',
            unique_together={('exam', 'category', 'subject')},
        ),
    ]
