# Generated by Django 5.1.3 on 2026-08-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_alter_examrequirement_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenrollment',
            name='break_grace_period',
            field=models.BooleanField(default=False, verbose_name='Quebra de carência'),
        ),
    ]
