# Generated by Django 5.1.3 on 2026-08-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_examenrollment_break_grace_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenrollment',
            name='break_waiting_period_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da quebra de carência'),
        ),
    ]
