# Generated by Django 5.1.3 on 2024-12-17 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('graduations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=15)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('celPhone', models.CharField(max_length=60)),
                ('graduation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='GraduacaoSensei', to='graduations.graduation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
