# Generated by Django 5.1.3 on 2026-02-04 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DojoMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Sensei Responsável'), ('ADMIN', 'Administrador'), ('STUDENT', 'Aluno')], default='STUDENT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='dojos.dojo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dojo_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vínculo com Dojo',
                'verbose_name_plural': 'Vínculos com Dojo',
                'unique_together': {('user', 'dojo')},
            },
        ),
    ]
