# Generated by Django 5.1.3 on 2026-02-04 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0002_dojomembership'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DojoMembership',
        ),
    ]
