# Generated by Django 5.1.3 on 2026-02-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0004_dojomembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojomembership',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
