# Generated by Django 5.1.3 on 2026-02-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0005_dojomembership_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojomembership',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Sensei Responsável'), ('ADMIN', 'Administrador'), ('EXAMINER', 'Examinador'), ('STUDENT', 'Aluno')], default='STUDENT', max_length=20),
        ),
    ]
