# Generated by Django 5.1.3 on 2026-04-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0006_alter_dojomembership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojomembership',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Sensei Responsável'), ('ADMIN', 'Administrador'), ('EXAMINER', 'Examinador'), ('STUDENT', 'Aluno'), ('SENSEI', 'Sensei')], default='STUDENT', max_length=20),
        ),
    ]
