# Generated by Django 5.1.3 on 2026-02-23 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dojos', '0006_alter_dojomembership_role'),
        ('karatecas', '0006_remove_karateca_monthlypay_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_date', models.DateField()),
                ('present', models.BooleanField(default=True, help_text='True = presente | False = falta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_attendances', to='dojos.dojo')),
                ('karateca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_attendances', to='karatecas.karateca')),
            ],
            options={
                'verbose_name': 'Training Attendance',
                'verbose_name_plural': 'Training Attendances',
                'ordering': ['-training_date'],
                'unique_together': {('karateca', 'dojo', 'training_date')},
            },
        ),
    ]
