# Generated by Django 5.1.3 on 2026-05-29 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('dojos', '0007_alter_dojomembership_role'),
        ('karatecas', '0008_karateca_birth_date'),
        ('trainings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trainingattendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='classes.aula'),
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='checkin_type',
            field=models.CharField(choices=[('QR', 'QR Code'), ('MANUAL', 'Manual')], default='QR', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='trainingattendance',
            unique_together={('karateca', 'aula', 'training_date')},
        ),
        migrations.CreateModel(
            name='TrainingCheckinSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_sessions', to='classes.aula')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_sessions', to='dojos.dojo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
