# Generated by Django 5.1.3 on 2026-05-29 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('trainings', '0002_alter_trainingattendance_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingattendance',
            name='checkin_type',
        ),
        migrations.AlterField(
            model_name='trainingattendance',
            name='aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_attendances', to='classes.aula'),
        ),
    ]
