# Generated by Django 5.1.3 on 2024-12-17 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kindrevenues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('duedate', models.DateField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenues', to='kindrevenues.kindrevenue')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
