# Generated by Django 5.1.3 on 2024-12-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
