# Generated by Django 5.1.3 on 2024-12-19 18:16

import revenues.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenues', '0002_alter_revenue_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='duedate',
            field=models.CharField(help_text='Insira dia e mês DD-MM', max_length=5, validators=[revenues.models.validate_day_month]),
        ),
    ]
