# Generated by Django 5.1.3 on 2024-12-18 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inflow',
            old_name='total_revenue',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='inflow',
            name='quantity',
        ),
    ]
