# Generated by Django 5.1.3 on 2024-12-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0002_rename_total_revenue_inflow_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflow',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
