# Generated by Django 5.1.3 on 2025-11-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingCycle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingcycle',
            options={'ordering': ['-year', '-month']},
        ),
        migrations.AddField(
            model_name='billingcycle',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingcycle',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
