# Generated by Django 5.1.3 on 2025-11-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingCycle', '0002_alter_billingcycle_options_billingcycle_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingcycle',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billingcycle',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='billingcycle',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
