# Generated by Django 5.1.3 on 2026-02-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduation',
            name='min_months',
            field=models.PositiveSmallIntegerField(blank=True, default=6, help_text='Meses mínimos de carência para próximo exame', null=True),
        ),
        migrations.AddField(
            model_name='graduation',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='graduation',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
