# Generated by Django 5.1.3 on 2026-03-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduations', '0002_graduation_min_months_graduation_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduation',
            name='min_months',
            field=models.PositiveSmallIntegerField(default=6, help_text='Meses mínimos de carência para próximo exame'),
        ),
        migrations.AlterField(
            model_name='graduation',
            name='name',
            field=models.CharField(default=20260101, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='graduation',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
