# Generated by Django 5.1.3 on 2026-03-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduations', '0003_alter_graduation_min_months_alter_graduation_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduation',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
