# Generated by Django 5.1.3 on 2024-12-17 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('karatestyles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namekata', models.CharField(max_length=100)),
                ('qtde_moviments', models.IntegerField()),
                ('file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('link', models.URLField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='styles', to='karatestyles.karatestyle')),
            ],
            options={
                'ordering': ['namekata'],
            },
        ),
    ]
